### ISSUE TITLE
主机页面报错TypeError: Cannot read property 'color' of undefined

### ISSUE THREAD

**Issue by pc439527** [canghai908/zbxtable#24]
> TypeError: Cannot read property 'color' of undefined
    at render (http://192.168.73.104:8088/js/views_srcManage_groups_jsx-views_srcManage_index_jsx-views_srcManage_templates_jsx-views_syst-0b9ab8_ce2659e1.chunk.js:1:5892)
    at http://192.168.73.104:8088/js/vendors-node_modules_antd_es_table_index_js-node_modules_antd_es_table_style_css_js_64a8fca4.chunk.js:1:85085
    at Ki (http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:59001)
    at Oa (http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:66957)
    at vo (http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:107423)
    at cu (http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:97723)
    at ou (http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:97648)
    at Zo (http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:94678)
    at http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:46385
    at t.unstable_runWithPriority (http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:127518)
    at Wl (http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:46094)
    at Bl (http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:46330)
    at Hl (http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:46265)
    at qo (http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:91463)
    at ma (http://192.168.73.104:8088/js/react-vendors-node_modules_react-dom_index_js_59df9e09.js:2:63345)
    at http://192.168.73.104:8088/js/vendors-node_modules_ant-design_icons_es_icons_AlertOutlined_js-node_modules_ant-design_icons-e9b21a_59df9e09.js:2:156754
![微信截图_20210814161109](https://user-images.githubusercontent.com/71417700/129439685-4ada988f-649e-4fe2-aed8-5fb838f02540.png)

**Comment by canghai908** [comment]
这个是由于5.4版本兼容问题

**Comment by pc439527** [comment]
> 这个是由于5.4版本兼容问题

好的 谢谢 哈 第一次装 就选了最新 原来问题还挺多

**Comment by canghai908** [comment]
@pc439527 已修复，更新到最新的v1.1.5版本即可解决。

**Comment by pc439527** [comment]
牛逼 谢谢
